#!/bin/bash

[[ $1 =~ ^cloud|parallel$ ]] || {
    printf "USAGE: %s cloud|parallel\n" "$0"
    exit 1
}

MODE=$1

OPTS=()

[[ $MODE == parallel ]] && OPTS+=(-P)

exec bash do.sh smts smt infra-all ${OPTS[@]} -n
